# Generated by Django 4.1.3 on 2022-12-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=3)),
                ('sold', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Discount Sales',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('zip', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('discount', models.IntegerField(blank=True)),
                ('products', models.TextField(max_length=300)),
                ('time', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(auto_now=True)),
                ('delivery', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Order Info',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=3)),
                ('sold', models.IntegerField()),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='SalesWithoutDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=3)),
                ('sold', models.IntegerField()),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Sales Without Discount',
            },
        ),
    ]
