# Generated by Django 4.1.3 on 2022-12-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountsales',
            options={'verbose_name_plural': 'Discount Sales'},
        ),
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'verbose_name_plural': 'Order Info'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterModelOptions(
            name='saleswithoutdiscount',
            options={'verbose_name_plural': 'Sales Without Discount'},
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
