# Generated by Django 4.1.3 on 2022-12-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_discountsales_options_alter_orderinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='quantity',
            field=models.TextField(default=1, max_length=300),
        ),
    ]
