# Generated by Django 4.1.3 on 2022-12-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_orderinfo_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='quantity',
            new_name='amount',
        ),
    ]
