# Generated by Django 4.1.3 on 2022-12-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_orderinfo_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountsales',
            options={'ordering': ['product_id', 'discount'], 'verbose_name_plural': 'Discount Sales'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['product_id'], 'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterModelOptions(
            name='saleswithoutdiscount',
            options={'ordering': ['product_id'], 'verbose_name_plural': 'Sales Without Discount'},
        ),
    ]
