# Generated by Django 4.1.3 on 2022-12-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_discountsales_options_alter_sales_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountsales',
            name='product_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='product_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='saleswithoutdiscount',
            name='product_id',
            field=models.IntegerField(),
        ),
    ]
